// Generated by xidl-bindgen. Do not edit by hand.
package window;

/**
 * Representations of one thing, by MIME type, which `write` puts on the
 * clipboard together so that a reader takes the richest it understands:
 * `text/plain` beside `text/html`, or `image/png` beside `text/plain`.
 */
abstract ClipboardItems(Int) from Int to Int {
	public static inline function create():ClipboardItems return ClipboardItemsNative.create();
	public inline function add(mimeType:String, bytes:haxe.io.Bytes):Void ClipboardItemsNative.add(this, mimeType, bytes);
	/**
	 * Replaces the clipboard's contents with the items; whether the
	 * platform took them. The handle names nothing after.
	 */
	public inline function write():Bool return ClipboardItemsNative.write(this);
}

private extern class ClipboardItemsNative {
	@:hlNative("xwindow", "clipboard_items_create")
	public static function create():ClipboardItems;
	@:hlNative("xwindow", "clipboard_items_add")
	public static function add(self:Int, mimeType:String, bytes:haxe.io.Bytes):Void;
	@:hlNative("xwindow", "clipboard_items_write")
	public static function write(self:Int):Bool;
}
