// Generated by xidl-bindgen. Do not edit by hand.
package window;

abstract ClipboardItems(Int) from Int to Int {
	public static inline function create():ClipboardItems return ClipboardItemsNative.create();
	public inline function add(mimeType:String, bytes:haxe.io.Bytes):Void ClipboardItemsNative.add(this, mimeType, bytes);
	public inline function write():Bool return ClipboardItemsNative.write(this);
}

private extern class ClipboardItemsNative {
	@:hlNative("xwindow", "clipboard_items_create")
	public static function create():ClipboardItems;
	@:hlNative("xwindow", "clipboard_items_add")
	public static function add(self:Int, mimeType:String, bytes:haxe.io.Bytes):Void;
	@:hlNative("xwindow", "clipboard_items_write")
	public static function write(self:Int):Bool;
}
