// Generated by xidl-bindgen. Do not edit by hand.
package window;

enum abstract CursorIcon(Int) from Int to Int {
	var Default = 0;
	var ContextMenu = 1;
	var Help = 2;
	var Pointer = 3;
	var Progress = 4;
	var Wait = 5;
	var Cell = 6;
	var Crosshair = 7;
	var Text = 8;
	var VerticalText = 9;
	var Alias = 10;
	var Copy = 11;
	var Move = 12;
	var NoDrop = 13;
	var NotAllowed = 14;
	var Grab = 15;
	var Grabbing = 16;
	var EResize = 17;
	var NResize = 18;
	var NeResize = 19;
	var NwResize = 20;
	var SResize = 21;
	var SeResize = 22;
	var SwResize = 23;
	var WResize = 24;
	var EwResize = 25;
	var NsResize = 26;
	var NeswResize = 27;
	var NwseResize = 28;
	var ColResize = 29;
	var RowResize = 30;
	var AllScroll = 31;
	var ZoomIn = 32;
	var ZoomOut = 33;
	var DndAsk = 34;
	var AllResize = 35;
}
