// Generated by xidl-bindgen. Do not edit by hand.
package window;

/** A device's raw input, whichever window has focus. */
enum DeviceEvent {
	Added;
	Removed;
	MouseMotion(x:Float, y:Float);
	MouseWheel(delta:MouseScrollDelta);
	Motion(axis:haxe.Int64, value:Float);
	Button(button:haxe.Int64, state:MouseElementState);
	Key(physical_key:PhysicalKey, state:MouseElementState);
}
