// Generated by xidl-bindgen. Do not edit by hand.
package window;

/** When the platform delivers raw device events (`Event.Device`). */
enum abstract DeviceEvents(Int) from Int to Int {
	var Always = 0;
	var WhenFocused = 1;
	var Never = 2;
}
