// Generated by xidl-bindgen. Do not edit by hand.
package window;

enum Event {
	None;
	Closed;
	Destroyed;
	Resized(width:haxe.Int64, height:haxe.Int64);
	Moved(x:Int, y:Int);
	Focused(focused:Bool);
	Occluded(occluded:Bool);
	ScaleFactorChanged(scale_factor:Float);
	ThemeChanged(theme:Theme);
	RedrawRequested;
	CursorEntered(device_id:Int);
	CursorLeft(device_id:Int);
	CursorMoved(x:Float, y:Float, device_id:Int);
	MouseInput(state:MouseElementState, button:MouseButton, device_id:Int);
	MouseWheel(delta:MouseScrollDelta, phase:TouchPhase, device_id:Int);
	KeyboardInput(device_id:Int, event:KeyEvent, is_synthetic:Bool);
	ModifiersChanged(modifiers:Modifiers);
	Ime(event:Ime);
	DroppedFile(path:FilePath);
	HoveredFile(path:FilePath);
	HoveredFileCancelled;
	PinchGesture(device_id:Int, delta:Float, phase:TouchPhase);
	PanGesture(device_id:Int, x:Float, y:Float, phase:TouchPhase);
	DoubleTapGesture(device_id:Int);
	RotationGesture(device_id:Int, delta:Float, phase:TouchPhase);
	TouchpadPressure(device_id:Int, pressure:Float, stage:haxe.Int64);
	AxisMotion(device_id:Int, axis:haxe.Int64, value:Float);
	Touch(device_id:Int, phase:TouchPhase, x:Float, y:Float, force:TouchForce, id:haxe.Int64);
	ActivationTokenDone(serial:haxe.Int64, token:String);
	Device(device_id:Int, event:DeviceEvent);
	Resumed;
	Suspended;
	MemoryWarning;
	Paste;
}
