// Generated by xidl-bindgen. Do not edit by hand.
package window;

/**
 * What `Window.poll` and `Window.wait` return: the next event, or `None`.
 * `device_id` is a positive id per input device. Raw device events go to
 * the focused window, or the first one open when none has focus.
 */
enum Event {
	None;
	/** The window is asked to close. It stays open until `close`. */
	Closed;
	Destroyed;
	Resized(width:haxe.Int64, height:haxe.Int64);
	Moved(x:Int, y:Int);
	Focused(focused:Bool);
	Occluded(occluded:Bool);
	ScaleFactorChanged(scale_factor:Float);
	ThemeChanged(theme:Theme);
	RedrawRequested;
	CursorEntered(device_id:Int);
	CursorLeft(device_id:Int);
	CursorMoved(x:Float, y:Float, device_id:Int);
	MouseInput(state:MouseElementState, button:MouseButton, device_id:Int);
	MouseWheel(delta:MouseScrollDelta, phase:TouchPhase, device_id:Int);
	KeyboardInput(device_id:Int, event:KeyEvent, is_synthetic:Bool);
	ModifiersChanged(modifiers:Modifiers);
	Ime(event:Ime);
	DroppedFile(path:FilePath);
	HoveredFile(path:FilePath);
	HoveredFileCancelled;
	PinchGesture(device_id:Int, delta:Float, phase:TouchPhase);
	PanGesture(device_id:Int, x:Float, y:Float, phase:TouchPhase);
	DoubleTapGesture(device_id:Int);
	RotationGesture(device_id:Int, delta:Float, phase:TouchPhase);
	TouchpadPressure(device_id:Int, pressure:Float, stage:haxe.Int64);
	AxisMotion(device_id:Int, axis:haxe.Int64, value:Float);
	/** All 64 bits of the touch's id. */
	Touch(device_id:Int, phase:TouchPhase, x:Float, y:Float, force:TouchForce, id:haxe.Int64);
	/** The token for the request `requestActivationToken` numbered `serial`. */
	ActivationTokenDone(serial:haxe.Int64, token:String);
	Device(device_id:Int, event:DeviceEvent);
	Resumed;
	Suspended;
	MemoryWarning;
	/**
	 * In a page, the user pasted: `clipboardText`, `clipboardTypeCount`,
	 * `clipboardType` and `clipboardData` answer what was pasted until the
	 * next paste, and the paste shortcut's key presses do not come. Other
	 * platforms send none: a program reads the clipboard when its paste
	 * shortcut is pressed.
	 */
	Paste;
}
