// Generated by xidl-bindgen. Do not edit by hand.
package window;

/**
 * A path as Unicode when it is; otherwise its exact bytes: a Unix path's,
 * or a Windows path's UTF-16 code units, little-endian. In a page, a
 * dropped file's name.
 */
enum FilePath {
	Utf8(path:String);
	UnixBytes(bytes:haxe.io.Bytes);
	WindowsWide(utf16le:haxe.io.Bytes);
}
