// Generated by xidl-bindgen. Do not edit by hand.
package window;

/** What an input method is told the text is for. */
enum abstract ImePurpose(Int) from Int to Int {
	var Normal = 0;
	var Password = 1;
	var Terminal = 2;
}
