// Generated by xidl-bindgen. Do not edit by hand.
package window;

enum KeyEvent {
	Input(physical_key:PhysicalKey, logical_key:Key, text:OptionalText, location:KeyLocation, state:MouseElementState, repeat:Bool, supplement:KeySupplement);
}
