// Generated by xidl-bindgen. Do not edit by hand.
package window;

/**
 * What the key would be without modifiers, and the text it types with all
 * of them, where the platform says.
 */
enum KeySupplement {
	Unavailable;
	Supplement(key_without_modifiers:Key, text_with_all_modifiers:OptionalText);
}
