// Generated by xidl-bindgen. Do not edit by hand.
package window;

/** The modifiers in effect, and which side of each is held. */
enum Modifiers {
	State(shift:Bool, control:Bool, alt:Bool, super_key:Bool, left_shift:ModifiersKeyState, right_shift:ModifiersKeyState, left_control:ModifiersKeyState, right_control:ModifiersKeyState, left_alt:ModifiersKeyState, right_alt:ModifiersKeyState, left_super:ModifiersKeyState, right_super:ModifiersKeyState);
}
