// Generated by xidl-bindgen. Do not edit by hand.
package window;

/** A display. The same display is the same handle. */
abstract Monitor(Int) from Int to Int {
	public inline function valid():Bool return MonitorNative.valid(this);
	public inline function name():String { var value = MonitorNative.name(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function width():Int return MonitorNative.width(this);
	public inline function height():Int return MonitorNative.height(this);
	public inline function x():Int return MonitorNative.x(this);
	public inline function y():Int return MonitorNative.y(this);
	public inline function scaleFactor():Float return MonitorNative.scaleFactor(this);
	/** Millihertz; zero when the platform does not say. */
	public inline function refreshRate():Int return MonitorNative.refreshRate(this);
	public inline function videoModeCount():Int return MonitorNative.videoModeCount(this);
	/** A video mode whose `valid` is false past the last. */
	public inline function videoMode(index:Int):VideoMode return MonitorNative.videoMode(this, index);
}

private extern class MonitorNative {
	@:hlNative("xwindow", "monitor_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xwindow", "monitor_name")
	public static function name(self:Int):hl.Bytes;
	@:hlNative("xwindow", "monitor_width")
	public static function width(self:Int):Int;
	@:hlNative("xwindow", "monitor_height")
	public static function height(self:Int):Int;
	@:hlNative("xwindow", "monitor_x")
	public static function x(self:Int):Int;
	@:hlNative("xwindow", "monitor_y")
	public static function y(self:Int):Int;
	@:hlNative("xwindow", "monitor_scale_factor")
	public static function scaleFactor(self:Int):Float;
	@:hlNative("xwindow", "monitor_refresh_rate")
	public static function refreshRate(self:Int):Int;
	@:hlNative("xwindow", "monitor_video_mode_count")
	public static function videoModeCount(self:Int):Int;
	@:hlNative("xwindow", "monitor_video_mode")
	public static function videoMode(self:Int, index:Int):VideoMode;
}
