// Generated by xidl-bindgen. Do not edit by hand.
package window;

abstract Monitor(Int) from Int to Int {
	public inline function valid():Bool return MonitorNative.valid(this);
	public inline function name():String { var value = MonitorNative.name(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function width():Int return MonitorNative.width(this);
	public inline function height():Int return MonitorNative.height(this);
	public inline function x():Int return MonitorNative.x(this);
	public inline function y():Int return MonitorNative.y(this);
	public inline function scaleFactor():Float return MonitorNative.scaleFactor(this);
	public inline function refreshRate():Int return MonitorNative.refreshRate(this);
}

private extern class MonitorNative {
	@:hlNative("xwindow", "monitor_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xwindow", "monitor_name")
	public static function name(self:Int):hl.Bytes;
	@:hlNative("xwindow", "monitor_width")
	public static function width(self:Int):Int;
	@:hlNative("xwindow", "monitor_height")
	public static function height(self:Int):Int;
	@:hlNative("xwindow", "monitor_x")
	public static function x(self:Int):Int;
	@:hlNative("xwindow", "monitor_y")
	public static function y(self:Int):Int;
	@:hlNative("xwindow", "monitor_scale_factor")
	public static function scaleFactor(self:Int):Float;
	@:hlNative("xwindow", "monitor_refresh_rate")
	public static function refreshRate(self:Int):Int;
}
