// Generated by xidl-bindgen. Do not edit by hand.
package window;

/**
 * Lines and rows of text, or pixels. Positive `y` scrolls the content
 * down the window, as winit reports.
 */
enum MouseScrollDelta {
	LineDelta(x:Float, y:Float);
	PixelDelta(x:Float, y:Float);
}
