// Generated by xidl-bindgen. Do not edit by hand.
package window;

/** Whether a key or button is down. */
enum abstract MouseElementState(Int) from Int to Int {
	var Pressed = 0;
	var Released = 1;
}
