// Generated by xidl-bindgen. Do not edit by hand.
package window;

/** A platform's code for a physical key winit does not name. */
enum NativeKeyCode {
	Unidentified;
	Android(code:haxe.Int64);
	MacOS(code:Int);
	Windows(code:Int);
	Xkb(code:haxe.Int64);
}
