// Generated by xidl-bindgen. Do not edit by hand.
package window;

enum NativeKey {
	Unidentified;
	Android(code:haxe.Int64);
	MacOS(code:Int);
	Windows(code:Int);
	Xkb(code:haxe.Int64);
	Web(key:String);
}
