// Generated by xidl-bindgen. Do not edit by hand.
package window;

/** A platform's code or name for a logical key winit does not name. */
enum NativeKey {
	Unidentified;
	Android(code:haxe.Int64);
	MacOS(code:Int);
	Windows(code:Int);
	Xkb(code:haxe.Int64);
	Web(key:String);
}
