// Generated by xidl-bindgen. Do not edit by hand.
package window;

/** The edge or corner `dragResizeWindow` resizes from. */
enum abstract ResizeDirection(Int) from Int to Int {
	var East = 0;
	var North = 1;
	var NorthEast = 2;
	var NorthWest = 3;
	var South = 4;
	var SouthEast = 5;
	var SouthWest = 6;
	var West = 7;
}
