// Generated by xidl-bindgen. Do not edit by hand.
package window;

/**
 * How a window's size follows a change of scale: `Logical` keeps its
 * logical size, as winit suggests; `Physical` keeps its size in pixels.
 */
enum abstract ScaleSizing(Int) from Int to Int {
	var Logical = 0;
	var Physical = 1;
}
