// Generated by xidl-bindgen. Do not edit by hand.
package window;

enum TouchForce {
	None;
	Calibrated(force:Float, max_possible_force:Float, altitude_angle:OptionalFloat);
	Normalized(force:Float);
}
