// Generated by xidl-bindgen. Do not edit by hand.
package window;

abstract VideoMode(Int) from Int to Int {
	public inline function valid():Bool return VideoModeNative.valid(this);
	public inline function width():Int return VideoModeNative.width(this);
	public inline function height():Int return VideoModeNative.height(this);
	public inline function bitDepth():Int return VideoModeNative.bitDepth(this);
	public inline function refreshRate():Int return VideoModeNative.refreshRate(this);
	public inline function monitor():Monitor return VideoModeNative.monitor(this);
}

private extern class VideoModeNative {
	@:hlNative("xwindow", "video_mode_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xwindow", "video_mode_width")
	public static function width(self:Int):Int;
	@:hlNative("xwindow", "video_mode_height")
	public static function height(self:Int):Int;
	@:hlNative("xwindow", "video_mode_bit_depth")
	public static function bitDepth(self:Int):Int;
	@:hlNative("xwindow", "video_mode_refresh_rate")
	public static function refreshRate(self:Int):Int;
	@:hlNative("xwindow", "video_mode_monitor")
	public static function monitor(self:Int):Monitor;
}
