// Generated by xidl-bindgen. Do not edit by hand.
package window;

abstract Window(Int) from Int to Int {
	/** A new window; one whose `valid` is false when the platform refuses. */
	public static inline function open(attributes:WindowAttributes):Window return WindowNative.open(attributes);
	public inline function valid():Bool return WindowNative.valid(this);
	/**
	 * When raw device events come, for every window: by default only while
	 * one of the program's windows has focus.
	 */
	public static inline function listenDeviceEvents(when:DeviceEvents):Void WindowNative.listenDeviceEvents(when);
	static inline function readOptionalText(index:Int):OptionalText {
		return switch (index) {
			case 1: OptionalText.Some(text(WindowNative.optionalTextSomeText()));
			default: OptionalText.None;
		};
	}
	/**
	 * The clipboard's text: none when it holds no text, no window is open,
	 * or the platform has no clipboard to read, as a page cannot.
	 */
	public static inline function clipboardText():OptionalText {
		return readOptionalText(WindowNative.clipboardTextVariant());
	}
	/** Puts text on the clipboard; nothing happens with no window open. */
	public static inline function setClipboardText(text:String):Void WindowNative.setClipboardText(text);
	/**
	 * How many types the clipboard holds now; `clipboardType` names each,
	 * best first, as a MIME type. `text/plain` is UTF-8 text and
	 * `text/uri-list` a list of files.
	 */
	public static inline function clipboardTypeCount():Int return WindowNative.clipboardTypeCount();
	public static inline function clipboardType(index:Int):String { var value = WindowNative.clipboardType(index); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	static inline function readOptionalBytes(index:Int):OptionalBytes {
		return switch (index) {
			case 1: OptionalBytes.Some(XidlBytes.take(WindowNative.optionalBytesSomeBytes()));
			default: OptionalBytes.None;
		};
	}
	/**
	 * The clipboard's bytes for a MIME type, or none when it does not hold
	 * it, no window is open, or the platform cannot read it.
	 */
	public static inline function clipboardData(mimeType:String):OptionalBytes {
		return readOptionalBytes(WindowNative.clipboardDataVariant(mimeType));
	}
	static inline function eventMouseInputButton():MouseButton {
		return switch (WindowNative.eventMouseInputButtonVariant()) {
			case 1: MouseButton.Right;
			case 2: MouseButton.Middle;
			case 3: MouseButton.Back;
			case 4: MouseButton.Forward;
			case 5: MouseButton.Other(WindowNative.eventMouseInputButtonOtherButton());
			default: MouseButton.Left;
		};
	}
	static inline function eventMouseWheelDelta():MouseScrollDelta {
		return switch (WindowNative.eventMouseWheelDeltaVariant()) {
			case 1: MouseScrollDelta.PixelDelta(WindowNative.eventMouseWheelDeltaPixelDeltaX(), WindowNative.eventMouseWheelDeltaPixelDeltaY());
			default: MouseScrollDelta.LineDelta(WindowNative.eventMouseWheelDeltaLineDeltaX(), WindowNative.eventMouseWheelDeltaLineDeltaY());
		};
	}
	static inline function eventKeyboardInputEventInputPhysicalKeyUnidentifiedCode():NativeKeyCode {
		return switch (WindowNative.eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeVariant()) {
			case 1: NativeKeyCode.Android(WindowNative.eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeAndroidCode());
			case 2: NativeKeyCode.MacOS(WindowNative.eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeMacOSCode());
			case 3: NativeKeyCode.Windows(WindowNative.eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeWindowsCode());
			case 4: NativeKeyCode.Xkb(WindowNative.eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeXkbCode());
			default: NativeKeyCode.Unidentified;
		};
	}
	static inline function eventKeyboardInputEventInputPhysicalKey():PhysicalKey {
		return switch (WindowNative.eventKeyboardInputEventInputPhysicalKeyVariant()) {
			case 1: PhysicalKey.Unidentified(eventKeyboardInputEventInputPhysicalKeyUnidentifiedCode());
			default: PhysicalKey.Code(WindowNative.eventKeyboardInputEventInputPhysicalKeyCodeCode());
		};
	}
	static inline function eventKeyboardInputEventInputLogicalKeyUnidentifiedKey():NativeKey {
		return switch (WindowNative.eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyVariant()) {
			case 1: NativeKey.Android(WindowNative.eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyAndroidCode());
			case 2: NativeKey.MacOS(WindowNative.eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyMacOSCode());
			case 3: NativeKey.Windows(WindowNative.eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyWindowsCode());
			case 4: NativeKey.Xkb(WindowNative.eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyXkbCode());
			case 5: NativeKey.Web(text(WindowNative.eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyWebKey()));
			default: NativeKey.Unidentified;
		};
	}
	static inline function eventKeyboardInputEventInputLogicalKeyDeadCharacter():OptionalText {
		return switch (WindowNative.eventKeyboardInputEventInputLogicalKeyDeadCharacterVariant()) {
			case 1: OptionalText.Some(text(WindowNative.eventKeyboardInputEventInputLogicalKeyDeadCharacterSomeText()));
			default: OptionalText.None;
		};
	}
	static inline function eventKeyboardInputEventInputLogicalKey():Key {
		return switch (WindowNative.eventKeyboardInputEventInputLogicalKeyVariant()) {
			case 1: Key.Character(text(WindowNative.eventKeyboardInputEventInputLogicalKeyCharacterText()));
			case 2: Key.Unidentified(eventKeyboardInputEventInputLogicalKeyUnidentifiedKey());
			case 3: Key.Dead(eventKeyboardInputEventInputLogicalKeyDeadCharacter());
			default: Key.Named(WindowNative.eventKeyboardInputEventInputLogicalKeyNamedKey());
		};
	}
	static inline function eventKeyboardInputEventInputText():OptionalText {
		return switch (WindowNative.eventKeyboardInputEventInputTextVariant()) {
			case 1: OptionalText.Some(text(WindowNative.eventKeyboardInputEventInputTextSomeText()));
			default: OptionalText.None;
		};
	}
	static inline function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKey():NativeKey {
		return switch (WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyVariant()) {
			case 1: NativeKey.Android(WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyAndroidCode());
			case 2: NativeKey.MacOS(WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyMacOSCode());
			case 3: NativeKey.Windows(WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyWindowsCode());
			case 4: NativeKey.Xkb(WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyXkbCode());
			case 5: NativeKey.Web(text(WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyWebKey()));
			default: NativeKey.Unidentified;
		};
	}
	static inline function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersDeadCharacter():OptionalText {
		return switch (WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersDeadCharacterVariant()) {
			case 1: OptionalText.Some(text(WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersDeadCharacterSomeText()));
			default: OptionalText.None;
		};
	}
	static inline function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiers():Key {
		return switch (WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersVariant()) {
			case 1: Key.Character(text(WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersCharacterText()));
			case 2: Key.Unidentified(eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKey());
			case 3: Key.Dead(eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersDeadCharacter());
			default: Key.Named(WindowNative.eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersNamedKey());
		};
	}
	static inline function eventKeyboardInputEventInputSupplementSupplementTextWithAllModifiers():OptionalText {
		return switch (WindowNative.eventKeyboardInputEventInputSupplementSupplementTextWithAllModifiersVariant()) {
			case 1: OptionalText.Some(text(WindowNative.eventKeyboardInputEventInputSupplementSupplementTextWithAllModifiersSomeText()));
			default: OptionalText.None;
		};
	}
	static inline function eventKeyboardInputEventInputSupplement():KeySupplement {
		return switch (WindowNative.eventKeyboardInputEventInputSupplementVariant()) {
			case 1: KeySupplement.Supplement(eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiers(), eventKeyboardInputEventInputSupplementSupplementTextWithAllModifiers());
			default: KeySupplement.Unavailable;
		};
	}
	static inline function eventKeyboardInputEvent():KeyEvent {
		return KeyEvent.Input(eventKeyboardInputEventInputPhysicalKey(), eventKeyboardInputEventInputLogicalKey(), eventKeyboardInputEventInputText(), WindowNative.eventKeyboardInputEventInputLocation(), WindowNative.eventKeyboardInputEventInputState(), WindowNative.eventKeyboardInputEventInputRepeat(), eventKeyboardInputEventInputSupplement());
	}
	static inline function eventModifiersChangedModifiers():Modifiers {
		return Modifiers.State(WindowNative.eventModifiersChangedModifiersStateShift(), WindowNative.eventModifiersChangedModifiersStateControl(), WindowNative.eventModifiersChangedModifiersStateAlt(), WindowNative.eventModifiersChangedModifiersStateSuperKey(), WindowNative.eventModifiersChangedModifiersStateLeftShift(), WindowNative.eventModifiersChangedModifiersStateRightShift(), WindowNative.eventModifiersChangedModifiersStateLeftControl(), WindowNative.eventModifiersChangedModifiersStateRightControl(), WindowNative.eventModifiersChangedModifiersStateLeftAlt(), WindowNative.eventModifiersChangedModifiersStateRightAlt(), WindowNative.eventModifiersChangedModifiersStateLeftSuper(), WindowNative.eventModifiersChangedModifiersStateRightSuper());
	}
	static inline function eventImeEventPreeditCursor():CursorRange {
		return switch (WindowNative.eventImeEventPreeditCursorVariant()) {
			case 1: CursorRange.Range(WindowNative.eventImeEventPreeditCursorRangeStart(), WindowNative.eventImeEventPreeditCursorRangeEnd());
			default: CursorRange.None;
		};
	}
	static inline function eventImeEvent():Ime {
		return switch (WindowNative.eventImeEventVariant()) {
			case 1: Ime.Preedit(text(WindowNative.eventImeEventPreeditText()), eventImeEventPreeditCursor());
			case 2: Ime.Commit(text(WindowNative.eventImeEventCommitText()));
			case 3: Ime.Disabled;
			default: Ime.Enabled;
		};
	}
	static inline function eventDroppedFilePath():FilePath {
		return switch (WindowNative.eventDroppedFilePathVariant()) {
			case 1: FilePath.UnixBytes(XidlBytes.take(WindowNative.eventDroppedFilePathUnixBytesBytes()));
			case 2: FilePath.WindowsWide(XidlBytes.take(WindowNative.eventDroppedFilePathWindowsWideUtf16le()));
			default: FilePath.Utf8(text(WindowNative.eventDroppedFilePathUtf8Path()));
		};
	}
	static inline function eventHoveredFilePath():FilePath {
		return switch (WindowNative.eventHoveredFilePathVariant()) {
			case 1: FilePath.UnixBytes(XidlBytes.take(WindowNative.eventHoveredFilePathUnixBytesBytes()));
			case 2: FilePath.WindowsWide(XidlBytes.take(WindowNative.eventHoveredFilePathWindowsWideUtf16le()));
			default: FilePath.Utf8(text(WindowNative.eventHoveredFilePathUtf8Path()));
		};
	}
	static inline function eventTouchForceCalibratedAltitudeAngle():OptionalFloat {
		return switch (WindowNative.eventTouchForceCalibratedAltitudeAngleVariant()) {
			case 1: OptionalFloat.Some(WindowNative.eventTouchForceCalibratedAltitudeAngleSomeValue());
			default: OptionalFloat.None;
		};
	}
	static inline function eventTouchForce():TouchForce {
		return switch (WindowNative.eventTouchForceVariant()) {
			case 1: TouchForce.Calibrated(WindowNative.eventTouchForceCalibratedForce(), WindowNative.eventTouchForceCalibratedMaxPossibleForce(), eventTouchForceCalibratedAltitudeAngle());
			case 2: TouchForce.Normalized(WindowNative.eventTouchForceNormalizedForce());
			default: TouchForce.None;
		};
	}
	static inline function eventDeviceEventMouseWheelDelta():MouseScrollDelta {
		return switch (WindowNative.eventDeviceEventMouseWheelDeltaVariant()) {
			case 1: MouseScrollDelta.PixelDelta(WindowNative.eventDeviceEventMouseWheelDeltaPixelDeltaX(), WindowNative.eventDeviceEventMouseWheelDeltaPixelDeltaY());
			default: MouseScrollDelta.LineDelta(WindowNative.eventDeviceEventMouseWheelDeltaLineDeltaX(), WindowNative.eventDeviceEventMouseWheelDeltaLineDeltaY());
		};
	}
	static inline function eventDeviceEventKeyPhysicalKeyUnidentifiedCode():NativeKeyCode {
		return switch (WindowNative.eventDeviceEventKeyPhysicalKeyUnidentifiedCodeVariant()) {
			case 1: NativeKeyCode.Android(WindowNative.eventDeviceEventKeyPhysicalKeyUnidentifiedCodeAndroidCode());
			case 2: NativeKeyCode.MacOS(WindowNative.eventDeviceEventKeyPhysicalKeyUnidentifiedCodeMacOSCode());
			case 3: NativeKeyCode.Windows(WindowNative.eventDeviceEventKeyPhysicalKeyUnidentifiedCodeWindowsCode());
			case 4: NativeKeyCode.Xkb(WindowNative.eventDeviceEventKeyPhysicalKeyUnidentifiedCodeXkbCode());
			default: NativeKeyCode.Unidentified;
		};
	}
	static inline function eventDeviceEventKeyPhysicalKey():PhysicalKey {
		return switch (WindowNative.eventDeviceEventKeyPhysicalKeyVariant()) {
			case 1: PhysicalKey.Unidentified(eventDeviceEventKeyPhysicalKeyUnidentifiedCode());
			default: PhysicalKey.Code(WindowNative.eventDeviceEventKeyPhysicalKeyCodeCode());
		};
	}
	static inline function eventDeviceEvent():DeviceEvent {
		return switch (WindowNative.eventDeviceEventVariant()) {
			case 1: DeviceEvent.Removed;
			case 2: DeviceEvent.MouseMotion(WindowNative.eventDeviceEventMouseMotionX(), WindowNative.eventDeviceEventMouseMotionY());
			case 3: DeviceEvent.MouseWheel(eventDeviceEventMouseWheelDelta());
			case 4: DeviceEvent.Motion(WindowNative.eventDeviceEventMotionAxis(), WindowNative.eventDeviceEventMotionValue());
			case 5: DeviceEvent.Button(WindowNative.eventDeviceEventButtonButton(), WindowNative.eventDeviceEventButtonState());
			case 6: DeviceEvent.Key(eventDeviceEventKeyPhysicalKey(), WindowNative.eventDeviceEventKeyState());
			default: DeviceEvent.Added;
		};
	}
	static inline function readEvent(index:Int):Event {
		return switch (index) {
			case 1: Event.Closed;
			case 2: Event.Destroyed;
			case 3: Event.Resized(WindowNative.eventResizedWidth(), WindowNative.eventResizedHeight());
			case 4: Event.Moved(WindowNative.eventMovedX(), WindowNative.eventMovedY());
			case 5: Event.Focused(WindowNative.eventFocusedFocused());
			case 6: Event.Occluded(WindowNative.eventOccludedOccluded());
			case 7: Event.ScaleFactorChanged(WindowNative.eventScaleFactorChangedScaleFactor());
			case 8: Event.ThemeChanged(WindowNative.eventThemeChangedTheme());
			case 9: Event.RedrawRequested;
			case 10: Event.CursorEntered(WindowNative.eventCursorEnteredDeviceId());
			case 11: Event.CursorLeft(WindowNative.eventCursorLeftDeviceId());
			case 12: Event.CursorMoved(WindowNative.eventCursorMovedX(), WindowNative.eventCursorMovedY(), WindowNative.eventCursorMovedDeviceId());
			case 13: Event.MouseInput(WindowNative.eventMouseInputState(), eventMouseInputButton(), WindowNative.eventMouseInputDeviceId());
			case 14: Event.MouseWheel(eventMouseWheelDelta(), WindowNative.eventMouseWheelPhase(), WindowNative.eventMouseWheelDeviceId());
			case 15: Event.KeyboardInput(WindowNative.eventKeyboardInputDeviceId(), eventKeyboardInputEvent(), WindowNative.eventKeyboardInputIsSynthetic());
			case 16: Event.ModifiersChanged(eventModifiersChangedModifiers());
			case 17: Event.Ime(eventImeEvent());
			case 18: Event.DroppedFile(eventDroppedFilePath());
			case 19: Event.HoveredFile(eventHoveredFilePath());
			case 20: Event.HoveredFileCancelled;
			case 21: Event.PinchGesture(WindowNative.eventPinchGestureDeviceId(), WindowNative.eventPinchGestureDelta(), WindowNative.eventPinchGesturePhase());
			case 22: Event.PanGesture(WindowNative.eventPanGestureDeviceId(), WindowNative.eventPanGestureX(), WindowNative.eventPanGestureY(), WindowNative.eventPanGesturePhase());
			case 23: Event.DoubleTapGesture(WindowNative.eventDoubleTapGestureDeviceId());
			case 24: Event.RotationGesture(WindowNative.eventRotationGestureDeviceId(), WindowNative.eventRotationGestureDelta(), WindowNative.eventRotationGesturePhase());
			case 25: Event.TouchpadPressure(WindowNative.eventTouchpadPressureDeviceId(), WindowNative.eventTouchpadPressurePressure(), WindowNative.eventTouchpadPressureStage());
			case 26: Event.AxisMotion(WindowNative.eventAxisMotionDeviceId(), WindowNative.eventAxisMotionAxis(), WindowNative.eventAxisMotionValue());
			case 27: Event.Touch(WindowNative.eventTouchDeviceId(), WindowNative.eventTouchPhase(), WindowNative.eventTouchX(), WindowNative.eventTouchY(), eventTouchForce(), WindowNative.eventTouchId());
			case 28: Event.ActivationTokenDone(WindowNative.eventActivationTokenDoneSerial(), text(WindowNative.eventActivationTokenDoneToken()));
			case 29: Event.Device(WindowNative.eventDeviceDeviceId(), eventDeviceEvent());
			case 30: Event.Resumed;
			case 31: Event.Suspended;
			case 32: Event.MemoryWarning;
			case 33: Event.Paste;
			default: Event.None;
		};
	}
	/**
	 * The next event, without waiting. It asks the platform for more only
	 * when the window has none queued and has answered none since the
	 * platform was last asked, so draining with polls asks once.
	 */
	public inline function poll():Event {
		return readEvent(WindowNative.pollVariant(this));
	}
	/**
	 * The next event, waiting up to `timeout` seconds for one; a negative
	 * timeout waits as long as it takes.
	 */
	public inline function wait(timeout:Float):Event {
		return readEvent(WindowNative.waitVariant(this, timeout));
	}
	/**
	 * Wake the current or next wait for application work, from any thread.
	 * Several calls coalesce; no synthetic window event is produced.
	 * False when no native event loop is available (including web hosts).
	 */
	public static inline function wake():Bool return WindowNative.wake();
	/**
	 * Coalesce cursor moves inside a caller-guaranteed quiet rectangle in
	 * physical pixels (left/top inclusive, right/bottom exclusive). No move
	 * is queued there; only its latest position is retained. Crossing the
	 * rectangle or receiving another window event resumes ordinary delivery.
	 * Empty or non-finite bounds disable coalescing. Raw device events are
	 * unaffected; applications using only window input can disable those.
	 */
	public inline function coalesceCursorMoves(left:Float, top:Float, right:Float, bottom:Float):Void WindowNative.coalesceCursorMoves(this, left, top, right, bottom);
	/**
	 * Disable coalescing and take the latest retained CursorMoved, or None.
	 * Call before changing hit geometry or processing application work.
	 * Other window events automatically deliver that position first.
	 */
	public inline function takeCursorMove():Event {
		return readEvent(WindowNative.takeCursorMoveVariant(this));
	}
	/** Close the window; its handle names nothing after. */
	public inline function close():Void WindowNative.close(this);
	/**
	 * The content's width in physical pixels; `setSize` takes logical
	 * ones, this over `scaleFactor`.
	 */
	public inline function width():Int return WindowNative.width(this);
	public inline function height():Int return WindowNative.height(this);
	public inline function outerWidth():Int return WindowNative.outerWidth(this);
	public inline function outerHeight():Int return WindowNative.outerHeight(this);
	/**
	 * Where the window's frame is, in physical pixels; `setPosition`
	 * takes logical ones, this over `scaleFactor`.
	 */
	public inline function x():Int return WindowNative.x(this);
	public inline function y():Int return WindowNative.y(this);
	/** Where the window's content is, without its frame. */
	public inline function innerX():Int return WindowNative.innerX(this);
	public inline function innerY():Int return WindowNative.innerY(this);
	public inline function scaleFactor():Float return WindowNative.scaleFactor(this);
	public inline function title():String { var value = WindowNative.title(this); return value == null ? null : @:privateAccess String.fromUCS2(value); };
	public inline function hasFocus():Bool return WindowNative.hasFocus(this);
	public inline function isVisible():Bool return WindowNative.isVisible(this);
	public inline function isMinimized():Bool return WindowNative.isMinimized(this);
	public inline function isMaximized():Bool return WindowNative.isMaximized(this);
	public inline function isFullscreen():Bool return WindowNative.isFullscreen(this);
	public inline function isResizable():Bool return WindowNative.isResizable(this);
	public inline function isDecorated():Bool return WindowNative.isDecorated(this);
	public inline function theme():Theme return WindowNative.theme(this);
	/**
	 * The window for a GPU surface: a platform code, and with `raw` the
	 * four integers xgpu's `GpuInstance.surface` takes after it. See
	 * xwindow-core's `raw` for the table.
	 */
	public inline function platform():Int return WindowNative.platform(this);
	public inline function raw(which:Int):haxe.Int64 return WindowNative.raw(this, which);
	public inline function setTitle(title:String):Void WindowNative.setTitle(this, title);
	/**
	 * The content's size in logical pixels: `width` and `height` over
	 * `scaleFactor`.
	 */
	public inline function setSize(width:Int, height:Int):Void WindowNative.setSize(this, width, height);
	/** A size of zero by zero removes the limit. */
	public inline function setMinSize(width:Int, height:Int):Void WindowNative.setMinSize(this, width, height);
	public inline function setMaxSize(width:Int, height:Int):Void WindowNative.setMaxSize(this, width, height);
	/**
	 * Move the window's frame to logical pixels: `x` and `y` over
	 * `scaleFactor`.
	 */
	public inline function setPosition(x:Int, y:Int):Void WindowNative.setPosition(this, x, y);
	public inline function setResizable(resizable:Bool):Void WindowNative.setResizable(this, resizable);
	public inline function setMinimized(minimized:Bool):Void WindowNative.setMinimized(this, minimized);
	public inline function setMaximized(maximized:Bool):Void WindowNative.setMaximized(this, maximized);
	public inline function setFullscreen(fullscreen:Bool):Void WindowNative.setFullscreen(this, fullscreen);
	public inline function setDecorations(decorations:Bool):Void WindowNative.setDecorations(this, decorations);
	public inline function setVisible(visible:Bool):Void WindowNative.setVisible(this, visible);
	public inline function setWindowLevel(level:WindowLevel):Void WindowNative.setWindowLevel(this, level);
	public inline function setTransparent(transparent:Bool):Void WindowNative.setTransparent(this, transparent);
	public inline function setBlur(blur:Bool):Void WindowNative.setBlur(this, blur);
	/**
	 * The system's shadow behind the window, on macOS and, for an
	 * undecorated window, Windows; elsewhere nothing.
	 */
	public inline function setHasShadow(hasShadow:Bool):Void WindowNative.setHasShadow(this, hasShadow);
	/**
	 * How far the background behind a transparent window is blurred, 0 for
	 * none: a radius on macOS, where `setBlur` means a radius of 80, and the
	 * platform's blur on or off elsewhere.
	 */
	public inline function setBlurRadius(radius:Int):Void WindowNative.setBlurRadius(this, radius);
	public inline function setContentProtected(protected:Bool):Void WindowNative.setContentProtected(this, protected);
	public inline function setScaleSizing(sizing:ScaleSizing):Void WindowNative.setScaleSizing(this, sizing);
	/** A theme, or none to follow the system's. */
	public inline function setTheme(theme:Null<Theme>):Void WindowNative.setThemeNative(this, (theme == null ? 0x80000000 : (theme : Int)));
	/** RGBA pixels, `width` by `height`; an empty buffer removes the icon. */
	public inline function setIcon(rgba:haxe.io.Bytes, width:Int, height:Int):Void WindowNative.setIcon(this, rgba, width, height);
	/** The steps a user resizes the window by; zero by zero removes them. */
	public inline function setResizeIncrements(width:Int, height:Int):Void WindowNative.setResizeIncrements(this, width, height);
	public inline function setEnabledButtons(close:Bool, minimize:Bool, maximize:Bool):Void WindowNative.setEnabledButtons(this, close, minimize, maximize);
	/** Fullscreen in a video mode of one of the window's monitors. */
	public inline function setExclusiveFullscreen(mode:VideoMode):Void WindowNative.setExclusiveFullscreen(this, mode);
	/**
	 * Move the window with the pointer while a button is held, as from an
	 * undecorated window's title bar; whether the platform started it.
	 */
	public inline function dragWindow():Bool return WindowNative.dragWindow(this);
	public inline function dragResizeWindow(direction:ResizeDirection):Bool return WindowNative.dragResizeWindow(this, direction);
	/** The system's window menu, at a logical position in the window. */
	public inline function showWindowMenu(x:Float, y:Float):Void WindowNative.showWindowMenu(this, x, y);
	public inline function requestRedraw():Void WindowNative.requestRedraw(this);
	/**
	 * Call just before presenting a frame. On Wayland the next
	 * `RedrawRequested` then waits for the compositor's frame callback for
	 * that frame, which paces drawing to the display; elsewhere it does
	 * nothing.
	 */
	public inline function prePresentNotify():Void WindowNative.prePresentNotify(this);
	public inline function focus():Void WindowNative.focus(this);
	public inline function requestAttention(attention:Attention):Void WindowNative.requestAttention(this, attention);
	public inline function setCursorIcon(icon:CursorIcon):Void WindowNative.setCursorIcon(this, icon);
	/**
	 * A cursor of `width` by `height` RGBA pixels, its hot spot at
	 * `hotX`, `hotY`.
	 */
	public inline function setCursorImage(rgba:haxe.io.Bytes, width:Int, height:Int, hotX:Int, hotY:Int):Void WindowNative.setCursorImage(this, rgba, width, height, hotX, hotY);
	public inline function setCursorVisible(visible:Bool):Void WindowNative.setCursorVisible(this, visible);
	/** Whether the platform took the grab. */
	public inline function setCursorGrab(grab:CursorGrab):Bool return WindowNative.setCursorGrab(this, grab);
	/**
	 * Whether pointer input reaches the window rather than passing
	 * through it; whether the platform took the setting.
	 */
	public inline function setCursorHittest(hittest:Bool):Bool return WindowNative.setCursorHittest(this, hittest);
	/** Whether the platform moved the cursor. */
	public inline function setCursorPosition(x:Float, y:Float):Bool return WindowNative.setCursorPosition(this, x, y);
	public inline function setImeAllowed(allowed:Bool):Void WindowNative.setImeAllowed(this, allowed);
	public inline function setImePurpose(purpose:ImePurpose):Void WindowNative.setImePurpose(this, purpose);
	public inline function setImeCursorArea(x:Float, y:Float, width:Float, height:Float):Void WindowNative.setImeCursorArea(this, x, y, width, height);
	/**
	 * A request's serial, which its `ActivationTokenDone` carries; zero
	 * where the platform has no activation tokens.
	 */
	public inline function requestActivationToken():haxe.Int64 return WindowNative.requestActivationToken(this);
	/** A monitor whose `valid` is false when there is none. */
	public inline function currentMonitor():Monitor return WindowNative.currentMonitor(this);
	public inline function primaryMonitor():Monitor return WindowNative.primaryMonitor(this);
	public inline function monitorCount():Int return WindowNative.monitorCount(this);
	public inline function monitor(index:Int):Monitor return WindowNative.monitor(this, index);
	static inline function text(value:hl.Bytes):String {
		return value == null ? null : @:privateAccess String.fromUCS2(value);
	}
}

private extern class WindowNative {
	@:hlNative("xwindow", "window_open")
	public static function open(attributes:WindowAttributes):Window;
	@:hlNative("xwindow", "window_valid")
	public static function valid(self:Int):Bool;
	@:hlNative("xwindow", "window_listen_device_events")
	public static function listenDeviceEvents(when:DeviceEvents):Void;
	@:hlNative("xwindow", "window_clipboard_text_variant")
	public static function clipboardTextVariant():Int;
	@:hlNative("xwindow", "window_optional_text_some_text")
	public static function optionalTextSomeText():hl.Bytes;
	@:hlNative("xwindow", "window_set_clipboard_text")
	public static function setClipboardText(text:String):Void;
	@:hlNative("xwindow", "window_clipboard_type_count")
	public static function clipboardTypeCount():Int;
	@:hlNative("xwindow", "window_clipboard_type")
	public static function clipboardType(index:Int):hl.Bytes;
	@:hlNative("xwindow", "window_clipboard_data_variant")
	public static function clipboardDataVariant(mimeType:String):Int;
	@:hlNative("xwindow", "window_optional_bytes_some_bytes")
	public static function optionalBytesSomeBytes():hl.Abstract<"xwindow_buffer_result">;
	@:hlNative("xwindow", "window_poll_variant")
	public static function pollVariant(self:Int):Int;
	@:hlNative("xwindow", "window_event_resized_width")
	public static function eventResizedWidth():haxe.Int64;
	@:hlNative("xwindow", "window_event_resized_height")
	public static function eventResizedHeight():haxe.Int64;
	@:hlNative("xwindow", "window_event_moved_x")
	public static function eventMovedX():Int;
	@:hlNative("xwindow", "window_event_moved_y")
	public static function eventMovedY():Int;
	@:hlNative("xwindow", "window_event_focused_focused")
	public static function eventFocusedFocused():Bool;
	@:hlNative("xwindow", "window_event_occluded_occluded")
	public static function eventOccludedOccluded():Bool;
	@:hlNative("xwindow", "window_event_scale_factor_changed_scale_factor")
	public static function eventScaleFactorChangedScaleFactor():Float;
	@:hlNative("xwindow", "window_event_theme_changed_theme")
	public static function eventThemeChangedTheme():Theme;
	@:hlNative("xwindow", "window_event_cursor_entered_device_id")
	public static function eventCursorEnteredDeviceId():Int;
	@:hlNative("xwindow", "window_event_cursor_left_device_id")
	public static function eventCursorLeftDeviceId():Int;
	@:hlNative("xwindow", "window_event_cursor_moved_x")
	public static function eventCursorMovedX():Float;
	@:hlNative("xwindow", "window_event_cursor_moved_y")
	public static function eventCursorMovedY():Float;
	@:hlNative("xwindow", "window_event_cursor_moved_device_id")
	public static function eventCursorMovedDeviceId():Int;
	@:hlNative("xwindow", "window_event_mouse_input_state")
	public static function eventMouseInputState():MouseElementState;
	@:hlNative("xwindow", "window_event_mouse_input_button_variant")
	public static function eventMouseInputButtonVariant():Int;
	@:hlNative("xwindow", "window_event_mouse_input_button_other_button")
	public static function eventMouseInputButtonOtherButton():Int;
	@:hlNative("xwindow", "window_event_mouse_input_device_id")
	public static function eventMouseInputDeviceId():Int;
	@:hlNative("xwindow", "window_event_mouse_wheel_delta_variant")
	public static function eventMouseWheelDeltaVariant():Int;
	@:hlNative("xwindow", "window_event_mouse_wheel_delta_line_delta_x")
	public static function eventMouseWheelDeltaLineDeltaX():Float;
	@:hlNative("xwindow", "window_event_mouse_wheel_delta_line_delta_y")
	public static function eventMouseWheelDeltaLineDeltaY():Float;
	@:hlNative("xwindow", "window_event_mouse_wheel_delta_pixel_delta_x")
	public static function eventMouseWheelDeltaPixelDeltaX():Float;
	@:hlNative("xwindow", "window_event_mouse_wheel_delta_pixel_delta_y")
	public static function eventMouseWheelDeltaPixelDeltaY():Float;
	@:hlNative("xwindow", "window_event_mouse_wheel_phase")
	public static function eventMouseWheelPhase():TouchPhase;
	@:hlNative("xwindow", "window_event_mouse_wheel_device_id")
	public static function eventMouseWheelDeviceId():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_device_id")
	public static function eventKeyboardInputDeviceId():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_variant")
	public static function eventKeyboardInputEventVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_physical_key_variant")
	public static function eventKeyboardInputEventInputPhysicalKeyVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_physical_key_code_code")
	public static function eventKeyboardInputEventInputPhysicalKeyCodeCode():KeyCode;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_physical_key_unidentified_code_variant")
	public static function eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_physical_key_unidentified_code_android_code")
	public static function eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeAndroidCode():haxe.Int64;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_physical_key_unidentified_code_mac_o_s_code")
	public static function eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeMacOSCode():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_physical_key_unidentified_code_windows_code")
	public static function eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeWindowsCode():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_physical_key_unidentified_code_xkb_code")
	public static function eventKeyboardInputEventInputPhysicalKeyUnidentifiedCodeXkbCode():haxe.Int64;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_variant")
	public static function eventKeyboardInputEventInputLogicalKeyVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_named_key")
	public static function eventKeyboardInputEventInputLogicalKeyNamedKey():NamedKey;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_character_text")
	public static function eventKeyboardInputEventInputLogicalKeyCharacterText():hl.Bytes;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_unidentified_key_variant")
	public static function eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_unidentified_key_android_code")
	public static function eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyAndroidCode():haxe.Int64;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_unidentified_key_mac_o_s_code")
	public static function eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyMacOSCode():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_unidentified_key_windows_code")
	public static function eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyWindowsCode():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_unidentified_key_xkb_code")
	public static function eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyXkbCode():haxe.Int64;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_unidentified_key_web_key")
	public static function eventKeyboardInputEventInputLogicalKeyUnidentifiedKeyWebKey():hl.Bytes;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_dead_character_variant")
	public static function eventKeyboardInputEventInputLogicalKeyDeadCharacterVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_logical_key_dead_character_some_text")
	public static function eventKeyboardInputEventInputLogicalKeyDeadCharacterSomeText():hl.Bytes;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_text_variant")
	public static function eventKeyboardInputEventInputTextVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_text_some_text")
	public static function eventKeyboardInputEventInputTextSomeText():hl.Bytes;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_location")
	public static function eventKeyboardInputEventInputLocation():KeyLocation;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_state")
	public static function eventKeyboardInputEventInputState():MouseElementState;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_repeat")
	public static function eventKeyboardInputEventInputRepeat():Bool;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_variant")
	public static function eventKeyboardInputEventInputSupplementVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_variant")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_named_key")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersNamedKey():NamedKey;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_character_text")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersCharacterText():hl.Bytes;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_unidentified_key_variant")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_unidentified_key_android_code")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyAndroidCode():haxe.Int64;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_unidentified_key_mac_o_s_code")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyMacOSCode():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_unidentified_key_windows_code")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyWindowsCode():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_unidentified_key_xkb_code")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyXkbCode():haxe.Int64;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_unidentified_key_web_key")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersUnidentifiedKeyWebKey():hl.Bytes;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_dead_character_variant")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersDeadCharacterVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_key_without_modifiers_dead_character_some_text")
	public static function eventKeyboardInputEventInputSupplementSupplementKeyWithoutModifiersDeadCharacterSomeText():hl.Bytes;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_text_with_all_modifiers_variant")
	public static function eventKeyboardInputEventInputSupplementSupplementTextWithAllModifiersVariant():Int;
	@:hlNative("xwindow", "window_event_keyboard_input_event_input_supplement_supplement_text_with_all_modifiers_some_text")
	public static function eventKeyboardInputEventInputSupplementSupplementTextWithAllModifiersSomeText():hl.Bytes;
	@:hlNative("xwindow", "window_event_keyboard_input_is_synthetic")
	public static function eventKeyboardInputIsSynthetic():Bool;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_variant")
	public static function eventModifiersChangedModifiersVariant():Int;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_shift")
	public static function eventModifiersChangedModifiersStateShift():Bool;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_control")
	public static function eventModifiersChangedModifiersStateControl():Bool;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_alt")
	public static function eventModifiersChangedModifiersStateAlt():Bool;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_super_key")
	public static function eventModifiersChangedModifiersStateSuperKey():Bool;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_left_shift")
	public static function eventModifiersChangedModifiersStateLeftShift():ModifiersKeyState;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_right_shift")
	public static function eventModifiersChangedModifiersStateRightShift():ModifiersKeyState;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_left_control")
	public static function eventModifiersChangedModifiersStateLeftControl():ModifiersKeyState;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_right_control")
	public static function eventModifiersChangedModifiersStateRightControl():ModifiersKeyState;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_left_alt")
	public static function eventModifiersChangedModifiersStateLeftAlt():ModifiersKeyState;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_right_alt")
	public static function eventModifiersChangedModifiersStateRightAlt():ModifiersKeyState;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_left_super")
	public static function eventModifiersChangedModifiersStateLeftSuper():ModifiersKeyState;
	@:hlNative("xwindow", "window_event_modifiers_changed_modifiers_state_right_super")
	public static function eventModifiersChangedModifiersStateRightSuper():ModifiersKeyState;
	@:hlNative("xwindow", "window_event_ime_event_variant")
	public static function eventImeEventVariant():Int;
	@:hlNative("xwindow", "window_event_ime_event_preedit_text")
	public static function eventImeEventPreeditText():hl.Bytes;
	@:hlNative("xwindow", "window_event_ime_event_preedit_cursor_variant")
	public static function eventImeEventPreeditCursorVariant():Int;
	@:hlNative("xwindow", "window_event_ime_event_preedit_cursor_range_start")
	public static function eventImeEventPreeditCursorRangeStart():haxe.Int64;
	@:hlNative("xwindow", "window_event_ime_event_preedit_cursor_range_end")
	public static function eventImeEventPreeditCursorRangeEnd():haxe.Int64;
	@:hlNative("xwindow", "window_event_ime_event_commit_text")
	public static function eventImeEventCommitText():hl.Bytes;
	@:hlNative("xwindow", "window_event_dropped_file_path_variant")
	public static function eventDroppedFilePathVariant():Int;
	@:hlNative("xwindow", "window_event_dropped_file_path_utf8_path")
	public static function eventDroppedFilePathUtf8Path():hl.Bytes;
	@:hlNative("xwindow", "window_event_dropped_file_path_unix_bytes_bytes")
	public static function eventDroppedFilePathUnixBytesBytes():hl.Abstract<"xwindow_buffer_result">;
	@:hlNative("xwindow", "window_event_dropped_file_path_windows_wide_utf16le")
	public static function eventDroppedFilePathWindowsWideUtf16le():hl.Abstract<"xwindow_buffer_result">;
	@:hlNative("xwindow", "window_event_hovered_file_path_variant")
	public static function eventHoveredFilePathVariant():Int;
	@:hlNative("xwindow", "window_event_hovered_file_path_utf8_path")
	public static function eventHoveredFilePathUtf8Path():hl.Bytes;
	@:hlNative("xwindow", "window_event_hovered_file_path_unix_bytes_bytes")
	public static function eventHoveredFilePathUnixBytesBytes():hl.Abstract<"xwindow_buffer_result">;
	@:hlNative("xwindow", "window_event_hovered_file_path_windows_wide_utf16le")
	public static function eventHoveredFilePathWindowsWideUtf16le():hl.Abstract<"xwindow_buffer_result">;
	@:hlNative("xwindow", "window_event_pinch_gesture_device_id")
	public static function eventPinchGestureDeviceId():Int;
	@:hlNative("xwindow", "window_event_pinch_gesture_delta")
	public static function eventPinchGestureDelta():Float;
	@:hlNative("xwindow", "window_event_pinch_gesture_phase")
	public static function eventPinchGesturePhase():TouchPhase;
	@:hlNative("xwindow", "window_event_pan_gesture_device_id")
	public static function eventPanGestureDeviceId():Int;
	@:hlNative("xwindow", "window_event_pan_gesture_x")
	public static function eventPanGestureX():Float;
	@:hlNative("xwindow", "window_event_pan_gesture_y")
	public static function eventPanGestureY():Float;
	@:hlNative("xwindow", "window_event_pan_gesture_phase")
	public static function eventPanGesturePhase():TouchPhase;
	@:hlNative("xwindow", "window_event_double_tap_gesture_device_id")
	public static function eventDoubleTapGestureDeviceId():Int;
	@:hlNative("xwindow", "window_event_rotation_gesture_device_id")
	public static function eventRotationGestureDeviceId():Int;
	@:hlNative("xwindow", "window_event_rotation_gesture_delta")
	public static function eventRotationGestureDelta():Float;
	@:hlNative("xwindow", "window_event_rotation_gesture_phase")
	public static function eventRotationGesturePhase():TouchPhase;
	@:hlNative("xwindow", "window_event_touchpad_pressure_device_id")
	public static function eventTouchpadPressureDeviceId():Int;
	@:hlNative("xwindow", "window_event_touchpad_pressure_pressure")
	public static function eventTouchpadPressurePressure():Float;
	@:hlNative("xwindow", "window_event_touchpad_pressure_stage")
	public static function eventTouchpadPressureStage():haxe.Int64;
	@:hlNative("xwindow", "window_event_axis_motion_device_id")
	public static function eventAxisMotionDeviceId():Int;
	@:hlNative("xwindow", "window_event_axis_motion_axis")
	public static function eventAxisMotionAxis():haxe.Int64;
	@:hlNative("xwindow", "window_event_axis_motion_value")
	public static function eventAxisMotionValue():Float;
	@:hlNative("xwindow", "window_event_touch_device_id")
	public static function eventTouchDeviceId():Int;
	@:hlNative("xwindow", "window_event_touch_phase")
	public static function eventTouchPhase():TouchPhase;
	@:hlNative("xwindow", "window_event_touch_x")
	public static function eventTouchX():Float;
	@:hlNative("xwindow", "window_event_touch_y")
	public static function eventTouchY():Float;
	@:hlNative("xwindow", "window_event_touch_force_variant")
	public static function eventTouchForceVariant():Int;
	@:hlNative("xwindow", "window_event_touch_force_calibrated_force")
	public static function eventTouchForceCalibratedForce():Float;
	@:hlNative("xwindow", "window_event_touch_force_calibrated_max_possible_force")
	public static function eventTouchForceCalibratedMaxPossibleForce():Float;
	@:hlNative("xwindow", "window_event_touch_force_calibrated_altitude_angle_variant")
	public static function eventTouchForceCalibratedAltitudeAngleVariant():Int;
	@:hlNative("xwindow", "window_event_touch_force_calibrated_altitude_angle_some_value")
	public static function eventTouchForceCalibratedAltitudeAngleSomeValue():Float;
	@:hlNative("xwindow", "window_event_touch_force_normalized_force")
	public static function eventTouchForceNormalizedForce():Float;
	@:hlNative("xwindow", "window_event_touch_id")
	public static function eventTouchId():haxe.Int64;
	@:hlNative("xwindow", "window_event_activation_token_done_serial")
	public static function eventActivationTokenDoneSerial():haxe.Int64;
	@:hlNative("xwindow", "window_event_activation_token_done_token")
	public static function eventActivationTokenDoneToken():hl.Bytes;
	@:hlNative("xwindow", "window_event_device_device_id")
	public static function eventDeviceDeviceId():Int;
	@:hlNative("xwindow", "window_event_device_event_variant")
	public static function eventDeviceEventVariant():Int;
	@:hlNative("xwindow", "window_event_device_event_mouse_motion_x")
	public static function eventDeviceEventMouseMotionX():Float;
	@:hlNative("xwindow", "window_event_device_event_mouse_motion_y")
	public static function eventDeviceEventMouseMotionY():Float;
	@:hlNative("xwindow", "window_event_device_event_mouse_wheel_delta_variant")
	public static function eventDeviceEventMouseWheelDeltaVariant():Int;
	@:hlNative("xwindow", "window_event_device_event_mouse_wheel_delta_line_delta_x")
	public static function eventDeviceEventMouseWheelDeltaLineDeltaX():Float;
	@:hlNative("xwindow", "window_event_device_event_mouse_wheel_delta_line_delta_y")
	public static function eventDeviceEventMouseWheelDeltaLineDeltaY():Float;
	@:hlNative("xwindow", "window_event_device_event_mouse_wheel_delta_pixel_delta_x")
	public static function eventDeviceEventMouseWheelDeltaPixelDeltaX():Float;
	@:hlNative("xwindow", "window_event_device_event_mouse_wheel_delta_pixel_delta_y")
	public static function eventDeviceEventMouseWheelDeltaPixelDeltaY():Float;
	@:hlNative("xwindow", "window_event_device_event_motion_axis")
	public static function eventDeviceEventMotionAxis():haxe.Int64;
	@:hlNative("xwindow", "window_event_device_event_motion_value")
	public static function eventDeviceEventMotionValue():Float;
	@:hlNative("xwindow", "window_event_device_event_button_button")
	public static function eventDeviceEventButtonButton():haxe.Int64;
	@:hlNative("xwindow", "window_event_device_event_button_state")
	public static function eventDeviceEventButtonState():MouseElementState;
	@:hlNative("xwindow", "window_event_device_event_key_physical_key_variant")
	public static function eventDeviceEventKeyPhysicalKeyVariant():Int;
	@:hlNative("xwindow", "window_event_device_event_key_physical_key_code_code")
	public static function eventDeviceEventKeyPhysicalKeyCodeCode():KeyCode;
	@:hlNative("xwindow", "window_event_device_event_key_physical_key_unidentified_code_variant")
	public static function eventDeviceEventKeyPhysicalKeyUnidentifiedCodeVariant():Int;
	@:hlNative("xwindow", "window_event_device_event_key_physical_key_unidentified_code_android_code")
	public static function eventDeviceEventKeyPhysicalKeyUnidentifiedCodeAndroidCode():haxe.Int64;
	@:hlNative("xwindow", "window_event_device_event_key_physical_key_unidentified_code_mac_o_s_code")
	public static function eventDeviceEventKeyPhysicalKeyUnidentifiedCodeMacOSCode():Int;
	@:hlNative("xwindow", "window_event_device_event_key_physical_key_unidentified_code_windows_code")
	public static function eventDeviceEventKeyPhysicalKeyUnidentifiedCodeWindowsCode():Int;
	@:hlNative("xwindow", "window_event_device_event_key_physical_key_unidentified_code_xkb_code")
	public static function eventDeviceEventKeyPhysicalKeyUnidentifiedCodeXkbCode():haxe.Int64;
	@:hlNative("xwindow", "window_event_device_event_key_state")
	public static function eventDeviceEventKeyState():MouseElementState;
	@:hlNative("xwindow", "window_wait_variant")
	public static function waitVariant(self:Int, timeout:Float):Int;
	@:hlNative("xwindow", "window_wake")
	public static function wake():Bool;
	@:hlNative("xwindow", "window_coalesce_cursor_moves")
	public static function coalesceCursorMoves(self:Int, left:Float, top:Float, right:Float, bottom:Float):Void;
	@:hlNative("xwindow", "window_take_cursor_move_variant")
	public static function takeCursorMoveVariant(self:Int):Int;
	@:hlNative("xwindow", "window_close")
	public static function close(self:Int):Void;
	@:hlNative("xwindow", "window_width")
	public static function width(self:Int):Int;
	@:hlNative("xwindow", "window_height")
	public static function height(self:Int):Int;
	@:hlNative("xwindow", "window_outer_width")
	public static function outerWidth(self:Int):Int;
	@:hlNative("xwindow", "window_outer_height")
	public static function outerHeight(self:Int):Int;
	@:hlNative("xwindow", "window_x")
	public static function x(self:Int):Int;
	@:hlNative("xwindow", "window_y")
	public static function y(self:Int):Int;
	@:hlNative("xwindow", "window_inner_x")
	public static function innerX(self:Int):Int;
	@:hlNative("xwindow", "window_inner_y")
	public static function innerY(self:Int):Int;
	@:hlNative("xwindow", "window_scale_factor")
	public static function scaleFactor(self:Int):Float;
	@:hlNative("xwindow", "window_title")
	public static function title(self:Int):hl.Bytes;
	@:hlNative("xwindow", "window_has_focus")
	public static function hasFocus(self:Int):Bool;
	@:hlNative("xwindow", "window_is_visible")
	public static function isVisible(self:Int):Bool;
	@:hlNative("xwindow", "window_is_minimized")
	public static function isMinimized(self:Int):Bool;
	@:hlNative("xwindow", "window_is_maximized")
	public static function isMaximized(self:Int):Bool;
	@:hlNative("xwindow", "window_is_fullscreen")
	public static function isFullscreen(self:Int):Bool;
	@:hlNative("xwindow", "window_is_resizable")
	public static function isResizable(self:Int):Bool;
	@:hlNative("xwindow", "window_is_decorated")
	public static function isDecorated(self:Int):Bool;
	@:hlNative("xwindow", "window_theme")
	public static function theme(self:Int):Theme;
	@:hlNative("xwindow", "window_platform")
	public static function platform(self:Int):Int;
	@:hlNative("xwindow", "window_raw")
	public static function raw(self:Int, which:Int):haxe.Int64;
	@:hlNative("xwindow", "window_set_title")
	public static function setTitle(self:Int, title:String):Void;
	@:hlNative("xwindow", "window_set_size")
	public static function setSize(self:Int, width:Int, height:Int):Void;
	@:hlNative("xwindow", "window_set_min_size")
	public static function setMinSize(self:Int, width:Int, height:Int):Void;
	@:hlNative("xwindow", "window_set_max_size")
	public static function setMaxSize(self:Int, width:Int, height:Int):Void;
	@:hlNative("xwindow", "window_set_position")
	public static function setPosition(self:Int, x:Int, y:Int):Void;
	@:hlNative("xwindow", "window_set_resizable")
	public static function setResizable(self:Int, resizable:Bool):Void;
	@:hlNative("xwindow", "window_set_minimized")
	public static function setMinimized(self:Int, minimized:Bool):Void;
	@:hlNative("xwindow", "window_set_maximized")
	public static function setMaximized(self:Int, maximized:Bool):Void;
	@:hlNative("xwindow", "window_set_fullscreen")
	public static function setFullscreen(self:Int, fullscreen:Bool):Void;
	@:hlNative("xwindow", "window_set_decorations")
	public static function setDecorations(self:Int, decorations:Bool):Void;
	@:hlNative("xwindow", "window_set_visible")
	public static function setVisible(self:Int, visible:Bool):Void;
	@:hlNative("xwindow", "window_set_window_level")
	public static function setWindowLevel(self:Int, level:WindowLevel):Void;
	@:hlNative("xwindow", "window_set_transparent")
	public static function setTransparent(self:Int, transparent:Bool):Void;
	@:hlNative("xwindow", "window_set_blur")
	public static function setBlur(self:Int, blur:Bool):Void;
	@:hlNative("xwindow", "window_set_has_shadow")
	public static function setHasShadow(self:Int, hasShadow:Bool):Void;
	@:hlNative("xwindow", "window_set_blur_radius")
	public static function setBlurRadius(self:Int, radius:Int):Void;
	@:hlNative("xwindow", "window_set_content_protected")
	public static function setContentProtected(self:Int, protected:Bool):Void;
	@:hlNative("xwindow", "window_set_scale_sizing")
	public static function setScaleSizing(self:Int, sizing:ScaleSizing):Void;
	@:hlNative("xwindow", "window_set_theme_native")
	public static function setThemeNative(self:Int, theme:Int):Void;
	@:hlNative("xwindow", "window_set_icon")
	public static function setIcon(self:Int, rgba:haxe.io.Bytes, width:Int, height:Int):Void;
	@:hlNative("xwindow", "window_set_resize_increments")
	public static function setResizeIncrements(self:Int, width:Int, height:Int):Void;
	@:hlNative("xwindow", "window_set_enabled_buttons")
	public static function setEnabledButtons(self:Int, close:Bool, minimize:Bool, maximize:Bool):Void;
	@:hlNative("xwindow", "window_set_exclusive_fullscreen")
	public static function setExclusiveFullscreen(self:Int, mode:VideoMode):Void;
	@:hlNative("xwindow", "window_drag_window")
	public static function dragWindow(self:Int):Bool;
	@:hlNative("xwindow", "window_drag_resize_window")
	public static function dragResizeWindow(self:Int, direction:ResizeDirection):Bool;
	@:hlNative("xwindow", "window_show_window_menu")
	public static function showWindowMenu(self:Int, x:Float, y:Float):Void;
	@:hlNative("xwindow", "window_request_redraw")
	public static function requestRedraw(self:Int):Void;
	@:hlNative("xwindow", "window_pre_present_notify")
	public static function prePresentNotify(self:Int):Void;
	@:hlNative("xwindow", "window_focus")
	public static function focus(self:Int):Void;
	@:hlNative("xwindow", "window_request_attention")
	public static function requestAttention(self:Int, attention:Attention):Void;
	@:hlNative("xwindow", "window_set_cursor_icon")
	public static function setCursorIcon(self:Int, icon:CursorIcon):Void;
	@:hlNative("xwindow", "window_set_cursor_image")
	public static function setCursorImage(self:Int, rgba:haxe.io.Bytes, width:Int, height:Int, hotX:Int, hotY:Int):Void;
	@:hlNative("xwindow", "window_set_cursor_visible")
	public static function setCursorVisible(self:Int, visible:Bool):Void;
	@:hlNative("xwindow", "window_set_cursor_grab")
	public static function setCursorGrab(self:Int, grab:CursorGrab):Bool;
	@:hlNative("xwindow", "window_set_cursor_hittest")
	public static function setCursorHittest(self:Int, hittest:Bool):Bool;
	@:hlNative("xwindow", "window_set_cursor_position")
	public static function setCursorPosition(self:Int, x:Float, y:Float):Bool;
	@:hlNative("xwindow", "window_set_ime_allowed")
	public static function setImeAllowed(self:Int, allowed:Bool):Void;
	@:hlNative("xwindow", "window_set_ime_purpose")
	public static function setImePurpose(self:Int, purpose:ImePurpose):Void;
	@:hlNative("xwindow", "window_set_ime_cursor_area")
	public static function setImeCursorArea(self:Int, x:Float, y:Float, width:Float, height:Float):Void;
	@:hlNative("xwindow", "window_request_activation_token")
	public static function requestActivationToken(self:Int):haxe.Int64;
	@:hlNative("xwindow", "window_current_monitor")
	public static function currentMonitor(self:Int):Monitor;
	@:hlNative("xwindow", "window_primary_monitor")
	public static function primaryMonitor(self:Int):Monitor;
	@:hlNative("xwindow", "window_monitor_count")
	public static function monitorCount(self:Int):Int;
	@:hlNative("xwindow", "window_monitor")
	public static function monitor(self:Int, index:Int):Monitor;
}
