// Generated by xidl-bindgen. Do not edit by hand.
package window;

abstract WindowAttributes(hl.Abstract<"xwindow_WindowAttributes">) {
	public inline function new() this = WindowAttributesNative.create();
	public inline function title(value:String):Void WindowAttributesNative.title(this, value);
	public inline function width(value:Int):Void WindowAttributesNative.width(this, value);
	public inline function height(value:Int):Void WindowAttributesNative.height(this, value);
	public inline function minWidth(value:Int):Void WindowAttributesNative.minWidth(this, value);
	public inline function minHeight(value:Int):Void WindowAttributesNative.minHeight(this, value);
	public inline function maxWidth(value:Int):Void WindowAttributesNative.maxWidth(this, value);
	public inline function maxHeight(value:Int):Void WindowAttributesNative.maxHeight(this, value);
	public inline function x(value:Int):Void WindowAttributesNative.x(this, value);
	public inline function y(value:Int):Void WindowAttributesNative.y(this, value);
	public inline function resizable(value:Bool):Void WindowAttributesNative.resizable(this, value);
	public inline function maximized(value:Bool):Void WindowAttributesNative.maximized(this, value);
	public inline function visible(value:Bool):Void WindowAttributesNative.visible(this, value);
	public inline function decorations(value:Bool):Void WindowAttributesNative.decorations(this, value);
	public inline function transparent(value:Bool):Void WindowAttributesNative.transparent(this, value);
	public inline function blur(value:Bool):Void WindowAttributesNative.blur(this, value);
	public inline function contentProtected(value:Bool):Void WindowAttributesNative.contentProtected(this, value);
	public inline function fullscreen(value:Bool):Void WindowAttributesNative.fullscreen(this, value);
	public inline function active(value:Bool):Void WindowAttributesNative.active(this, value);
	public inline function windowLevel(value:WindowLevel):Void WindowAttributesNative.windowLevel(this, value);
	public inline function theme(value:Theme):Void WindowAttributesNative.theme(this, value);
	public inline function scaleSizing(value:ScaleSizing):Void WindowAttributesNative.scaleSizing(this, value);
}

private extern class WindowAttributesNative {
	@:hlNative("xwindow", "window_attributes_new")
	public static function create():hl.Abstract<"xwindow_WindowAttributes">;
	@:hlNative("xwindow", "window_attributes_title")
	public static function title(self:hl.Abstract<"xwindow_WindowAttributes">, value:String):Void;
	@:hlNative("xwindow", "window_attributes_width")
	public static function width(self:hl.Abstract<"xwindow_WindowAttributes">, value:Int):Void;
	@:hlNative("xwindow", "window_attributes_height")
	public static function height(self:hl.Abstract<"xwindow_WindowAttributes">, value:Int):Void;
	@:hlNative("xwindow", "window_attributes_min_width")
	public static function minWidth(self:hl.Abstract<"xwindow_WindowAttributes">, value:Int):Void;
	@:hlNative("xwindow", "window_attributes_min_height")
	public static function minHeight(self:hl.Abstract<"xwindow_WindowAttributes">, value:Int):Void;
	@:hlNative("xwindow", "window_attributes_max_width")
	public static function maxWidth(self:hl.Abstract<"xwindow_WindowAttributes">, value:Int):Void;
	@:hlNative("xwindow", "window_attributes_max_height")
	public static function maxHeight(self:hl.Abstract<"xwindow_WindowAttributes">, value:Int):Void;
	@:hlNative("xwindow", "window_attributes_x")
	public static function x(self:hl.Abstract<"xwindow_WindowAttributes">, value:Int):Void;
	@:hlNative("xwindow", "window_attributes_y")
	public static function y(self:hl.Abstract<"xwindow_WindowAttributes">, value:Int):Void;
	@:hlNative("xwindow", "window_attributes_resizable")
	public static function resizable(self:hl.Abstract<"xwindow_WindowAttributes">, value:Bool):Void;
	@:hlNative("xwindow", "window_attributes_maximized")
	public static function maximized(self:hl.Abstract<"xwindow_WindowAttributes">, value:Bool):Void;
	@:hlNative("xwindow", "window_attributes_visible")
	public static function visible(self:hl.Abstract<"xwindow_WindowAttributes">, value:Bool):Void;
	@:hlNative("xwindow", "window_attributes_decorations")
	public static function decorations(self:hl.Abstract<"xwindow_WindowAttributes">, value:Bool):Void;
	@:hlNative("xwindow", "window_attributes_transparent")
	public static function transparent(self:hl.Abstract<"xwindow_WindowAttributes">, value:Bool):Void;
	@:hlNative("xwindow", "window_attributes_blur")
	public static function blur(self:hl.Abstract<"xwindow_WindowAttributes">, value:Bool):Void;
	@:hlNative("xwindow", "window_attributes_content_protected")
	public static function contentProtected(self:hl.Abstract<"xwindow_WindowAttributes">, value:Bool):Void;
	@:hlNative("xwindow", "window_attributes_fullscreen")
	public static function fullscreen(self:hl.Abstract<"xwindow_WindowAttributes">, value:Bool):Void;
	@:hlNative("xwindow", "window_attributes_active")
	public static function active(self:hl.Abstract<"xwindow_WindowAttributes">, value:Bool):Void;
	@:hlNative("xwindow", "window_attributes_window_level")
	public static function windowLevel(self:hl.Abstract<"xwindow_WindowAttributes">, value:WindowLevel):Void;
	@:hlNative("xwindow", "window_attributes_theme")
	public static function theme(self:hl.Abstract<"xwindow_WindowAttributes">, value:Theme):Void;
	@:hlNative("xwindow", "window_attributes_scale_sizing")
	public static function scaleSizing(self:hl.Abstract<"xwindow_WindowAttributes">, value:ScaleSizing):Void;
}
